controller_manager:
  ros__parameters:
    update_rate: 10 
    use_sim_time: true

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController #type of the controller, this indicates that we want to send trajectory commands to the arm joint

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # gripper_controller:
    #  type: forward_command_controller/ForwardCommandController #send single command

    joint_state_broadcaster: #publishes the current states of the joint to a topic
      type: joint_state_broadcaster/JointStateBroadcaster
   

arm_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  
    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

gripper_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - joint_8
      
    #interface_name: position

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true